<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use frontend\models\base\Event;
use Yii;

/**
 * This is the base-model class for table "donasi_event".
 *
 * @property integer $id
 * @property integer $event
 * @property integer $donatur
 * @property integer $jumlah
 * @property string $tanggal
 * @property integer $valid
 * @property string $tgl_valid
 * @property string $aliasModel
 */
abstract class DonasiEvent extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'donasi_event';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event', 'donatur', 'jumlah', 'valid'], 'integer'],
            [['tanggal'], 'string', 'max' => 100],
            [['tgl_valid'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'event' => 'Event',
            'donatur' => 'Donatur',
            'jumlah' => 'Jumlah',
            'tanggal' => 'Tanggal',
            'valid' => 'Valid',
            'tgl_valid' => 'Tgl Valid',
        ];
    }

    public function getNamaMhs()
    {
        return $this->hasOne(Mahasiswa::className(), ['id' => 'donatur']);
    }
    public function getEv()
    {
        return $this->hasOne(\frontend\models\Event::className(), ['id' => 'event']);
    }
}
