<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "event".
 *
 * @property integer $id
 * @property string $tittle
 * @property string $description
 * @property integer $id_location
 * @property string $image
 * @property integer $id_publisher
 * @property string $alamat
 * @property integer $id_kategori
 * @property integer $flag
 *
 * @property \frontend\models\Publisher $idPublisher
 * @property \frontend\models\Ticket $id0
 * @property \frontend\models\Kabupaten $idLocation
 * @property \frontend\models\KategoriEvent $idKategori
 * @property \frontend\models\Timeline[] $timelines
 * @property string $aliasModel
 */
abstract class Event extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tittle', 'description', 'id_location', 'image', 'id_publisher', 'alamat', 'id_kategori', 'flag'], 'required'],
            [['description'], 'string'],
            [['id_location', 'id_publisher', 'id_kategori', 'flag'], 'integer'],
            [['tittle', 'image', 'alamat'], 'string', 'max' => 255],
            [['id_publisher'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\Publisher::className(), 'targetAttribute' => ['id_publisher' => 'id']],
            [['id'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\Ticket::className(), 'targetAttribute' => ['id' => 'id_event']],
            [['id_location'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\Kabupaten::className(), 'targetAttribute' => ['id_location' => 'id_kab']],
            [['id_kategori'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\KategoriEvent::className(), 'targetAttribute' => ['id_kategori' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tittle' => 'Tittle',
            'description' => 'Description',
            'id_location' => 'Id Location',
            'image' => 'Image',
            'id_publisher' => 'Id Publisher',
            'alamat' => 'Alamat',
            'id_kategori' => 'Id Kategori',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdPublisher()
    {
        return $this->hasOne(\frontend\models\Publisher::className(), ['id' => 'id_publisher']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getId0()
    {
        return $this->hasOne(\frontend\models\Ticket::className(), ['id_event' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdLocation()
    {
        return $this->hasOne(\frontend\models\Kabupaten::className(), ['id_kab' => 'id_location']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdKategori()
    {
        return $this->hasOne(\frontend\models\KategoriEvent::className(), ['id' => 'id_kategori']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTimelines()
    {
        return $this->hasMany(\frontend\models\Timeline::className(), ['id_event' => 'id']);
    }




}
