<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "jurusan".
 *
 * @property integer $id
 * @property integer $fakultas
 * @property string $nama_jurusan
 * @property string $aliasModel
 */
abstract class Jurusan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jurusan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fakultas', 'nama_jurusan'], 'required'],
            [['fakultas'], 'integer'],
            [['nama_jurusan'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fakultas' => 'Fakultas',
            'nama_jurusan' => 'Nama Jurusan',
        ];
    }
    

}
