<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "kabupaten".
 *
 * @property integer $id_kab
 * @property integer $id_prov
 * @property string $nama
 *
 * @property \frontend\models\Event[] $events
 * @property string $aliasModel
 */
abstract class Kabupaten extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kabupaten';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_kab', 'id_prov', 'nama'], 'required'],
            [['id_kab', 'id_prov'], 'integer'],
            [['nama'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_kab' => 'Id Kab',
            'id_prov' => 'Id Prov',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(\frontend\models\Event::className(), ['id_location' => 'id_kab']);
    }




}
