<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "kategori_event".
 *
 * @property integer $id
 * @property string $nama_event
 *
 * @property \frontend\models\Event[] $events
 * @property string $aliasModel
 */
abstract class KategoriEvent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kategori_event';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_event'], 'required'],
            [['nama_event'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_event' => 'Nama Event',
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(\frontend\models\Event::className(), ['id_kategori' => 'id']);
    }




}
