<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "kategori_forum".
 *
 * @property integer $id
 * @property string $nama_kategori
 * @property string $icon
 *
 * @property \frontend\models\Forum[] $forums
 * @property string $aliasModel
 */
abstract class KategoriForum extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kategori_forum';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_kategori', 'icon'], 'required'],
            [['nama_kategori', 'icon'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_kategori' => 'Nama Kategori',
            'icon' => 'Icon',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getForums()
    {
        return $this->hasMany(\frontend\models\Forum::className(), ['id_kategori_forum' => 'id']);
    }




}
