<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "master_categori".
 *
 * @property integer $id
 * @property string $nama
 * @property integer $valid
 *
 * @property \frontend\models\MhsMinat[] $mhsMinats
 * @property string $aliasModel
 */
abstract class MasterCategori extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_categori';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['valid'], 'integer'],
            [['nama'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'valid' => 'Valid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMhsMinats()
    {
        return $this->hasMany(\frontend\models\MhsMinat::className(), ['categori_id' => 'id']);
    }




}
