<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "master_mitra".
 *
 * @property integer $id
 * @property integer $id_kota
 * @property integer $id_provinsi
 * @property string $nama
 * @property string $email
 * @property string $alamat
 * @property string $kontak
 * @property integer $id_user
 * @property integer $id_kategori
 * @property string $status_spk
 *
 * @property \app\models\MasterKegiatan[] $masterKegiatans
 * @property \app\models\MasterKontrak[] $masterKontraks
 * @property \app\models\Skenario1[] $skenario1s
 * @property \app\models\MasterKategoriMitra $idKategori
 * @property \app\models\User $idUser
 * @property string $aliasModel
 */
abstract class MasterMitra extends \yii\db\ActiveRecord
{
    public $kuota;
    public $nominal;
    public $id_skenario;
    public $diambil;
    public $request;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_mitra';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_kota', 'id_provinsi', 'nama', 'email', 'alamat', 'kontak', 'id_user', 'id_kategori', 'status_spk'], 'required'],
            [['id_user', 'id_kategori','id_provinsi','id_kota'], 'integer'],
          
            [['id_kategori'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterKategoriMitra::className(), 'targetAttribute' => ['id_kategori' => 'id']],
             [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['id_user' => 'id']],
           [['nama'], 'string', 'max' => 100],
            [['email', 'kontak'], 'string', 'max' => 50],
            [['alamat'], 'string', 'max' => 255],
            [['status_spk'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_kota' => 'Id Kota',
            'id_provinsi' => 'Id Provinsi',
            'nama' => 'Nama',
            'email' => 'Email',
            'alamat' => 'Alamat',
            'kontak' => 'Kontak',
            'id_user' => 'Id User',
            'id_kategori' => 'Id Kategori',
            'status_spk' => 'Status Spk',
        ];
    }

     /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdKategori()
    {
        return $this->hasOne(\app\models\MasterKategoriMitra::className(), ['id' => 'id_kategori']);
    }
     /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterKegiatans()
    {
        return $this->hasMany(\app\models\MasterKegiatan::className(), ['id_mitra' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterKontraks()
    {
        return $this->hasMany(\app\models\MasterKontrak::className(), ['id_mitra' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSkenario1s()
    {
        return $this->hasMany(\app\models\Skenario1::className(), ['id_mitra' => 'id']);
    }

}
