<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "master_kontrak".
 *
 * @property integer $id
 * @property string $nama
 * @property integer $id_mitra
 * @property string $nilai_kontrak
 * @property string $tanggal_mulai
 * @property string $tanggal_berakhir
 * @property integer $status
 * @property integer $flag
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \app\models\MasterKegiatan[] $masterKegiatans
 * @property \app\models\MasterMitra $idMitra
 * @property string $aliasModel
 */
abstract class MasterKontrak extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_kontrak';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'id_mitra', 'nilai_kontrak', 'tanggal_mulai', 'tanggal_berakhir', 'status', 'flag'], 'required'],
            [['id_mitra', 'nilai_kontrak', 'status', 'flag'], 'integer'],
            [['tanggal_mulai', 'tanggal_berakhir'], 'safe'],
            [['nama'], 'string', 'max' => 50],
            [['id_mitra'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterMitra::className(), 'targetAttribute' => ['id_mitra' => 'id']],
            ['tanggal_mulai', 'compare', 'compareAttribute' => 'tanggal_berakhir', 'operator' => '<', 'enableClientValidation' => false],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama Kontrak',
            'id_mitra' => 'Mitra',
            'nilai_kontrak' => 'Nilai Kontrak',
            'tanggal_mulai' => 'Tanggal Mulai',
            'tanggal_berakhir' => 'Tanggal Berakhir',
            'status' => 'Status',
            'flag' => 'Flag',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterKegiatans()
    {
        return $this->hasMany(\frontend\models\MasterKegiatan::className(), ['id_kontrak' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdMitra()
    {
        return $this->hasOne(\frontend\models\MasterMitra::className(), ['id' => 'id_mitra']);
    }




}
