<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "master_ruang_lingkup".
 *
 * @property integer $id
 * @property string $nama
 *
 * @property \frontend\models\MasterPerusahaan[] $masterPerusahaans
 * @property \frontend\models\MhsPekerjaan[] $mhsPekerjaans
 * @property string $aliasModel
 */
abstract class MasterRuangLingkup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_ruang_lingkup';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['nama'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterPerusahaans()
    {
        return $this->hasMany(\frontend\models\MasterPerusahaan::className(), ['ruang_lingkup' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMhsPekerjaans()
    {
        return $this->hasMany(\frontend\models\MhsPekerjaan::className(), ['ruang_lingkup' => 'id']);
    }




}
