<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "master_perusahaan".
 *
 * @property integer $id
 * @property string $nama
 * @property string $alamat
 * @property integer $ruang_lingkup
 *
 * @property \frontend\models\MasterRuangLingkup $ruangLingkup
 * @property \frontend\models\MhsPekerjaan[] $mhsPekerjaans
 * @property string $aliasModel
 */
abstract class MasterPerusahaan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_perusahaan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'alamat', 'ruang_lingkup'], 'required'],
            [['ruang_lingkup'], 'integer'],
            [['nama'], 'string', 'max' => 100],
            [['alamat'], 'string', 'max' => 255],
            [['ruang_lingkup'], 'exist', 'skipOnError' => true, 'targetClass' => MasterRuangLingkup::className(), 'targetAttribute' => ['ruang_lingkup' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'alamat' => 'Alamat',
            'ruang_lingkup' => 'Ruang Lingkup',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuangLingkup()
    {
        return $this->hasOne(\frontend\models\MasterRuangLingkup::className(), ['id' => 'ruang_lingkup']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMhsPekerjaans()
    {
        return $this->hasMany(\frontend\models\MhsPekerjaan::className(), ['perusahaan_id' => 'id']);
    }




}
