<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "mhs_minat".
 *
 * @property integer $id
 * @property integer $categori_id
 *
 * @property \frontend\models\MasterCategori $categori
 * @property string $aliasModel
 */
abstract class MhsMinat extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mhs_minat';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['categori_id'], 'required'],
            [['categori_id'], 'integer'],
            [['categori_id'], 'exist', 'skipOnError' => true, 'targetClass' => MasterCategori::className(), 'targetAttribute' => ['categori_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'categori_id' => 'Categori ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategori()
    {
        return $this->hasOne(\frontend\models\MasterCategori::className(), ['id' => 'categori_id']);
    }




}
