<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "mhs_pekerjaan".
 *
 * @property integer $id
 * @property integer $mahasiswa_id
 * @property integer $perusahaan_id
 * @property string $nama_perusahaan
 * @property integer $ruang_lingkup
 * @property string $lokasi
 * @property string $posisi
 * @property string $deskripsi
 * @property string $tanggal_mulai
 * @property string $tanggal_akhir
 *
 * @property \frontend\models\Mahasiswa $mahasiswa
 * @property \frontend\models\MasterPerusahaan $perusahaan
 * @property \frontend\models\MasterRuangLingkup $ruangLingkup
 * @property string $aliasModel
 */
abstract class MhsPekerjaan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mhs_pekerjaan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ruang_lingkup', 'lokasi', 'posisi', 'tanggal_mulai'], 'required'],
            [['mahasiswa_id', 'perusahaan_id', 'ruang_lingkup'], 'integer'],
            [['deskripsi'], 'string'],
            [['tanggal_mulai', 'tanggal_akhir'], 'safe'],
            [['nama_perusahaan', 'lokasi'], 'string', 'max' => 150],
            [['posisi','long','lat','status'], 'string', 'max' => 100],
            [['mahasiswa_id'], 'exist', 'skipOnError' => true, 'targetClass' => Mahasiswa::className(), 'targetAttribute' => ['mahasiswa_id' => 'id']],
            [['perusahaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => MasterPerusahaan::className(), 'targetAttribute' => ['perusahaan_id' => 'id']],
            [['ruang_lingkup'], 'exist', 'skipOnError' => true, 'targetClass' => MasterRuangLingkup::className(), 'targetAttribute' => ['ruang_lingkup' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mahasiswa_id' => 'Mahasiswa',
            'perusahaan_id' => 'Perusahaan',
            'nama_perusahaan' => 'Nama Perusahaan',
            'ruang_lingkup' => 'Ruang Lingkup',
            'lokasi' => 'Lokasi',
            'long' => 'long',
            'lat' => 'lat',
            'posisi' => 'Posisi',
            'status' => 'Status',
            'deskripsi' => 'Deskripsi',
            'tanggal_mulai' => 'Tanggal Mulai',
            'tanggal_akhir' => 'Tanggal Akhir',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMahasiswa()
    {
        return $this->hasOne(\frontend\models\Mahasiswa::className(), ['id' => 'mahasiswa_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerusahaan()
    {
        return $this->hasOne(\frontend\models\MasterPerusahaan::className(), ['id' => 'perusahaan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuangLingkup()
    {
        return $this->hasOne(\frontend\models\MasterRuangLingkup::className(), ['id' => 'ruang_lingkup']);
    }




}
