<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "publisher".
 *
    * @property integer $id
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $password
* @property string $description 
* @property string $alamat 
* @property integer $flag 
* @property integer $id_user 
 *
 * @property \frontend\models\Event[] $events
 * @property string $aliasModel
 */
abstract class Publisher extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'publisher';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           [['name', 'phone', 'email', 'password', 'description', 'alamat', 'flag'], 'required'],
           [['flag', 'id_user'], 'integer'],
           [['name', 'email'], 'string', 'max' => 50],
           [['phone'], 'string', 'max' => 20],
           [['password'], 'string', 'max' => 100],
           [['description', 'alamat'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
             'id' => 'ID',
            'name' => 'Name',
            'phone' => 'Phone',
            'email' => 'Email',
            'password' => 'Password',
              'description' => 'Description', 
           'alamat' => 'Alamat', 
           'flag' => 'Flag', 
           'id_user' => 'Id User', 
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
         return $this->hasMany(\frontend\models\Event::className(), ['id_publisher' => 'id']);
    }




}
