<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace api\modules\v1\models;

use Yii;

/**
 * This is the base-model class for table "provinsi".
 *
 * @property integer $id_prov
 * @property string $nama
 * @property string $aliasModel
 */
class DaftarPenyakit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'daftar_penyakit';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_penyakit', 'id'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'nama_penyakit' => 'Nama Penyakit',
            'id' => 'id',
        ];
    }

}
