<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace api\modules\v1\models;

use Yii;

/**
 * This is the base-model class for table "provinsi".
 *
 * @property integer $id_prov
 * @property string $nama
 * @property string $aliasModel
 */
class Provinsi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'provinsi';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_prov', 'nama'], 'required'],
            [['id_prov'], 'integer'],
            [['nama'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_prov' => 'Id Prov',
            'nama' => 'Nama',
        ];
    }




}
