<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var frontend\models\Event $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Event');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Events'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->title, 'url' => ['view', 'id_event' => $model->id_event]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud event-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('models', 'Event') ?>
        <small>
            <?= $model->title ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
            [ 'update', 'id_event' => $model->id_event],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
            ['create', 'id_event' => $model->id_event, 'Event'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('frontend\models\Event'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id_location',
        'id_timeline:datetime',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_publisher',
    'value' => ($model->getIdPublisher()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['publisher/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getIdPublisher()->one()->name, ['publisher/view', 'id_publisher' => $model->getIdPublisher()->one()->id_publisher,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Event'=>['id_publisher' => $model->id_publisher]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'title',
        'description',
        'poster_path',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id_event' => $model->id_event],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->id_event.'</b>',
    'content' => $this->blocks['frontend\models\Event'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
