<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use yii\helpers\ArrayHelper;
use app\models\Publisher;

/**
* @var yii\web\View $this
* @var app\models\Event $model
* @var yii\widgets\ActiveForm $form
*/

?>
<div class="box box-warning">
   <div class="box-body">

<div class="event-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Event',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
<!-- attribute id_user -->
<?php
    $id_user = Yii::$app->user->identity->id;
    $id_publish= Publisher::find()->andWhere('id_user = '.$id_user)->one();
?>

<!-- attribute title -->
			<?= $form->field($model, 'tittle')->textInput(['maxlength' => true]) ?>

<!-- attribute description -->
			<?= $form->field($model, 'description')->textArea(['maxlength' => true]) ?>
            <!-- attribute id_kategori -->
           <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_kategori')->dropDownList(
   \yii\helpers\ArrayHelper::map(app\models\KategoriEvent::find()->all(), 'id', 'nama_event'),
   [
       'prompt' => 'Select',
       'disabled' => (isset($relAttributes) && isset($relAttributes['id_kategori'])),
   ]
)->label('kategori event'); ?>

<!-- attribute poster_path -->
            <?= $form->field($model, 'file1')->fileInput()->label("Poster") ?>
            <!-- attribute alamat -->
           <?= $form->field($model, 'alamat')->textArea(['maxlength' => true]) ?>
<!-- attribute id_location -->
            <!--  -->
                   <?= $form->field($model, 'id_location')->widget(\kartik\select2\Select2::className(),[
                'data'=>ArrayHelper::map(app\models\Kabupaten::find()->all(),'id_kab','nama'),
                'options'=>[
                    'prompt'=>'Pilih Kota'
                ],
            ])->label('Kota');  ?>

            <?= $form->field($model, 'id_publisher')->hiddenInput(['value'=>$id_publish->id])->label(false) ?>

            <?= $form->field($model, 'flag')->hiddenInput(['value'=>1])->label(false) ?>

        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   =>  'Event',
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
</div>
</div>
