<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "customer".
 *
 * @property integer $id
 * @property string $name
 * @property string $phone
 * @property integer $id_user
 * @property string $email
 * 
 * @property \app\models\KategoriEvent $idKategori 
 * @property string $password
 * @property string $aliasModel
 */
abstract class Customer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           [['name', 'phone', 'email', 'password'], 'required'],
           [['id_user'], 'integer'],
           [['name', 'email'], 'string', 'max' => 50],
           [['phone'], 'string', 'max' => 15],
           [['password'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
             'id' => 'ID',
            'name' => 'Name',
            'phone' => 'Phone',
            'id_user' => 'Id User',
            'email' => 'Email',
            'password' => 'Password',
        ];
    }




}
