<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the base-model class for table "event".
 *
  * @property integer $id
* @property string $tittle
 * @property string $description
 * @property integer $id_location
* @property string $image
 * @property integer $id_publisher
   * @property string $alamat 
* @property integer $id_kategori 
* @property integer $flag 
 *
  * @property \app\models\Publisher $idPublisher 
 * @property \app\models\Kabupaten $idLocation
  * @property \app\models\KategoriEvent $idKategori
 * @property \app\models\Timeline[] $timelines
  * @property \app\models\Ticket[] $tickets
 * @property string $aliasModel

 */
abstract class Event extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public $file1;
    public static function tableName()
    {
      return 'event';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
      return [
        [['id_location','id_publisher'], 'integer'],
        [['tittle', 'description', 'id_location','id_publisher', 'alamat', 'id_kategori', 'flag'], 'required'],
        [['id_location'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Kabupaten::className(), 'targetAttribute' => ['id_location' => 'id_kab']],
        [['id_kategori'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\KategoriEvent::className(), 'targetAttribute' => ['id_kategori' => 'id']],
        [['file1'], 'file', 'extensions'=>'png,jpg'],
        [['id_publisher'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Publisher::className(), 'targetAttribute' => ['id_publisher' => 'id']]
      ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
      return [
        'id' => 'ID',
        'tittle' => 'Tittle',
        'description' => 'Description',
        'id_location' => 'Id Location',
        'image' => 'Image',
        'id_publisher' => 'Id Publisher', 
        'alamat' => 'Alamat', 
        'id_kategori' => 'Id Kategori', 
        'flag' => 'Flag', 
      ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdLocation()
    {
      return $this->hasOne(\app\models\Kabupaten::className(), ['id_kab' => 'id_location']);
    }
     /** 
    * @return \yii\db\ActiveQuery 
    */ 
     public function getIdPublisher() 
     { 
       return $this->hasOne(\app\models\Publisher::className(), ['id' => 'id_publisher']); 
     } 


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdKategori()
    {
      return $this->hasOne(\app\models\KategoriEvent::className(), ['id' => 'id_kategori']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTimelines()
    {
     return $this->hasMany(\app\models\Timeline::className(), ['id_event' => 'id']);
   }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTickets()
    {
     return $this->hasMany(\app\models\Ticket::className(), ['id_event' => 'id']);
   }

   public function beforeSave($insert){
    if(parent::beforeSave($insert)){
      if (Yii::$app->request->isPost) {
        $this->file1 = UploadedFile::getInstance($this, 'file1');
        if ($this->file1 && $this->validate()) {

          $this->file1->saveAs('uploads/event/' . $this->file1->baseName . '.' .$this->file1->extension);
          $this->image = 'uploads/event/'.$this->file1->baseName . '.' .$this->file1->extension;
          return true;
        }
      }
    }
    else{
      return false;
    }
  }
  public function getImageurl()
{
    return \Yii::$app->request->BaseUrl.'/'.$this->image;
}





}
