<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "history_timeline".
 *
 * @property integer $id_timeline
 * @property integer $id_event
 * @property string $timeline_name
 * @property string $description
 * @property string $timeline_category
 * @property string $held_at
 *
 * @property \app\models\HistoryTicket[] $historyTickets
 * @property \app\models\HistoryEvent $idEvent
 * @property string $aliasModel
 */
abstract class HistoryTimeline extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'history_timeline';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_event'], 'integer'],
            [['held_at'], 'safe'],
            [['timeline_name', 'description', 'timeline_category'], 'string', 'max' => 100],
            [['id_event'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\HistoryEvent::className(), 'targetAttribute' => ['id_event' => 'id_event']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_timeline' => 'Id Timeline',
            'id_event' => 'Id Event',
            'timeline_name' => 'Timeline Name',
            'description' => 'Description',
            'timeline_category' => 'Timeline Category',
            'held_at' => 'Held At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHistoryTickets()
    {
        return $this->hasMany(\app\models\HistoryTicket::className(), ['id_timeline' => 'id_timeline']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdEvent()
    {
        return $this->hasOne(\app\models\HistoryEvent::className(), ['id_event' => 'id_event']);
    }




}
