<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "history_ticket".
 *
 * @property integer $id_ticket
 * @property integer $id_timeline
 * @property integer $id_event
 * @property string $ticket_name
 * @property string $description
 * @property integer $price
 *
 * @property \app\models\HistoryTimeline $idTimeline
 * @property string $aliasModel
 */
abstract class HistoryTicket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'history_ticket';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_timeline', 'id_event', 'price'], 'integer'],
            [['ticket_name', 'description'], 'string', 'max' => 100],
            [['id_timeline'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\HistoryTimeline::className(), 'targetAttribute' => ['id_timeline' => 'id_timeline']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_ticket' => 'Id Ticket',
            'id_timeline' => 'Id Timeline',
            'id_event' => 'Id Event',
            'ticket_name' => 'Ticket Name',
            'description' => 'Description',
            'price' => 'Price',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdTimeline()
    {
        return $this->hasOne(\app\models\HistoryTimeline::className(), ['id_timeline' => 'id_timeline']);
    }




}
