<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "timeline".
 *
 * @property integer $id
 * @property integer $id_event
 * @property string $name
 * @property string $description
 * @property string $tanggal
 * @property integer $flag
 *
 * @property \app\models\Event $idEvent
 * @property string $aliasModel
 */
abstract class Timeline extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'timeline';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_event', 'name', 'description', 'tanggal', 'flag'], 'required'],
            [['id_event', 'flag'], 'integer'],
            [['description'], 'string'],
            [['tanggal'], 'safe'],
            [['name'], 'string', 'max' => 50],
            [['id_event'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Event::className(), 'targetAttribute' => ['id_event' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_event' => 'Id Event',
            'name' => 'Name',
            'description' => 'Description',
            'tanggal' => 'Tanggal',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdEvent()
    {
        return $this->hasOne(\app\models\Event::className(), ['id' => 'id_event']);
    }




}
